apiVersion: v1 
kind: Secret 
metadata: 
  name: user-secret
  namespace: aqua  
data: 
  username: <base64 username> 
  password: <base64 password>
  ## Mandatory for SaaS Environments:
  # token : <base64 aqua cloud connector authentication token>
